import type { Internship } from "@/types";

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: "1",
    title: "Software Engineering Intern",
    company: "Google",
    location: "Mountain View, CA (Hybrid)",
    tags: ["engineering", "backend", "python"],
    source: "linkedin",
    applyUrl: "https://careers.google.com",
    isCompetitive: true,
    requirements: ["Python", "Data Structures", "Algorithms", "Git"],
    salary: "$8,000/mo",
    postedAt: "2026-04-10",
    description:
      "Join Google's core engineering team to build scalable backend systems used by billions of people worldwide.",
    companySize: "enterprise",
  },
  {
    id: "2",
    title: "Product Design Intern",
    company: "Figma",
    location: "San Francisco, CA (Hybrid)",
    tags: ["design", "product", "ux"],
    source: "wellfound",
    applyUrl: "https://www.figma.com/careers",
    isCompetitive: true,
    requirements: ["Figma", "User Research", "Prototyping", "Visual Design"],
    salary: "$7,500/mo",
    postedAt: "2026-04-12",
    description:
      "Help shape the future of design tools by working alongside Figma's product design team.",
    companySize: "mid-size",
  },
  {
    id: "3",
    title: "Marketing Intern",
    company: "Notion",
    location: "Remote",
    tags: ["marketing", "content", "social media"],
    source: "themuse",
    applyUrl: "https://www.notion.so/careers",
    isCompetitive: false,
    requirements: ["Copywriting", "Social Media", "Analytics", "Canva"],
    salary: "$4,500/mo",
    postedAt: "2026-04-13",
    description:
      "Drive Notion's brand awareness through creative campaigns and community engagement.",
    companySize: "mid-size",
  },
  {
    id: "4",
    title: "Data Science Intern",
    company: "Spotify",
    location: "New York, NY (Hybrid)",
    tags: ["data", "analytics", "machine learning"],
    source: "handshake",
    applyUrl: "https://www.lifeatspotify.com",
    isCompetitive: true,
    requirements: ["Python", "SQL", "Machine Learning", "Statistics"],
    salary: "$7,000/mo",
    postedAt: "2026-04-08",
    description:
      "Use data to improve music recommendations for 600M+ Spotify listeners.",
    companySize: "enterprise",
  },
  {
    id: "5",
    title: "Finance Intern",
    company: "Stripe",
    location: "San Francisco, CA",
    tags: ["finance", "fintech", "analysis"],
    source: "linkedin",
    applyUrl: "https://stripe.com/jobs",
    isCompetitive: true,
    requirements: ["Excel", "Financial Modeling", "SQL", "Python"],
    salary: "$6,500/mo",
    postedAt: "2026-04-11",
    description:
      "Support Stripe's finance team with analysis, forecasting, and strategic planning.",
    companySize: "enterprise",
  },
  {
    id: "6",
    title: "Operations Intern",
    company: "Airbnb",
    location: "Remote",
    tags: ["operations", "business", "strategy"],
    source: "ripplematch",
    applyUrl: "https://careers.airbnb.com",
    isCompetitive: false,
    requirements: ["Project Management", "Excel", "Communication", "Research"],
    salary: "$5,000/mo",
    postedAt: "2026-04-14",
    description:
      "Support cross-functional operations projects that improve host and guest experiences.",
    companySize: "enterprise",
  },
  {
    id: "7",
    title: "Frontend Engineering Intern",
    company: "Linear",
    location: "Remote",
    tags: ["engineering", "frontend", "react"],
    source: "wellfound",
    applyUrl: "https://linear.app/careers",
    isCompetitive: false,
    requirements: ["React", "TypeScript", "CSS", "Git"],
    salary: "$6,000/mo",
    postedAt: "2026-04-09",
    description:
      "Build beautiful, fast UI for Linear's project management tool used by top engineering teams.",
    companySize: "startup",
  },
  {
    id: "8",
    title: "Brand & Communications Intern",
    company: "Duolingo",
    location: "Pittsburgh, PA (Hybrid)",
    tags: ["marketing", "brand", "writing"],
    source: "indeed",
    applyUrl: "https://careers.duolingo.com",
    isCompetitive: false,
    requirements: ["Copywriting", "Brand Strategy", "Social Media", "Canva"],
    salary: "$4,000/mo",
    postedAt: "2026-04-07",
    description:
      "Help tell Duolingo's story across social platforms and brand campaigns.",
    companySize: "mid-size",
  },
  {
    id: "9",
    title: "Machine Learning Intern",
    company: "OpenAI",
    location: "San Francisco, CA",
    tags: ["engineering", "machine learning", "ai"],
    source: "linkedin",
    applyUrl: "https://openai.com/careers",
    isCompetitive: true,
    requirements: ["Python", "PyTorch", "Machine Learning", "Mathematics", "Research"],
    salary: "$10,000/mo",
    postedAt: "2026-04-06",
    description:
      "Work on cutting-edge AI research and systems at the frontier of artificial intelligence.",
    companySize: "mid-size",
  },
  {
    id: "10",
    title: "Business Development Intern",
    company: "HubSpot",
    location: "Boston, MA (Hybrid)",
    tags: ["business", "sales", "growth"],
    source: "handshake",
    applyUrl: "https://www.hubspot.com/careers",
    isCompetitive: false,
    requirements: ["Communication", "Sales", "CRM", "Research", "Excel"],
    salary: "$3,500/mo",
    postedAt: "2026-04-13",
    description:
      "Partner with HubSpot's sales team to identify and develop new business opportunities.",
    companySize: "enterprise",
  },
];
